// ignore_for_file: constant_identifier_names

enum Area{
 FISICA, QUIMICA, GEOLOGIA, ASTRONOMIA, HIDROLOGIA, METEOROLOGIA, OCEANOGRAFIA, ECOLOGIA, BIOQUIMICA, MICROBIOLOGIA,
	BOTANICA, ZOOLOGIA,
	///
	PSICOLOGIA, SOCIOLOGIA, ANTROPOLOGIA, ECONOMIA, ARQUEOLOGIA, HISTORIA, GEOGRAFIA, DERECHA, POLITICA, FILOSOFIA,
	CRIMINOLOGIA,
	///
	MATEMATICA, LOGICA, INFORMATICA, ESTADISTICA, INTELIGENCIA_ARTIFICIAL, TECNOLOGIA_INFORMACION,
	///
	INGENIERIA, AGRICULTURA, ACUACULTURA, ARQUITECTURA,
	///
	TECNOLOGIA, DERECHO, SALUD, AGRONOMIA, VETERINARIA, CONTABILIDAD, ADMINISTRACION, OTRO;
}